authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, contacts, upload_to_base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('upload/', upload_to_base, name='upload'),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

products/urls.py
from django.urls import path
from .views import ProductListView, ProductView

app_name = 'products'

urlpatterns = [
   path('', ProductListView.as_view(), name='index'),
   path('category/<int:pk>/', ProductListView.as_view(), name='category'),
   path('category/<int:pk>/page/<int:page>/', ProductListView.as_view(), name='page'),
   path('product/<int:pk>/', ProductView.as_view(), name='product')
]

products/models.py
from django.db import models

from geekshop import utils


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=True, verbose_name='активность')

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(verbose_name='изображение', upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    is_active = models.BooleanField(default=True, verbose_name='активность')

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @property
    def get_price(self):
        return utils.get_price_format(self.price)


class TestModel(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name

products/views.py
# import json
from django.db import connection
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.views.generic import DetailView, ListView

from .models import ProductCategory, Product


def get_hot_product():
    return Product.objects.filter(is_active=True).order_by('?').first()


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


def get_catalog_menu():
    return ProductCategory.objects.filter(is_active=True)


class ProductListView(ListView):
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'
    ordering = ('price',)
    paginate_by = 3

    def get_queryset(self):
        query_set = super().get_queryset()

        if self.kwargs.get('pk') is None:
            return query_set

        if self.kwargs['pk'] == 0:
            return query_set.filter(is_active=True)
        else:
            return query_set.filter(category__pk=self.kwargs['pk'], is_active=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        category = None
        if self.kwargs.get('pk') is not None:
            category = ProductCategory.objects.filter(pk=self.kwargs['pk']).first()

        if category is None:
            category = ProductCategory(name='все', pk=0)

        context['title'] = 'продукты "'

        if self.kwargs.get('pk') is not None:
            context['title'] = 'продукты "' + category.name + '"'
            context['page_url'] = 'products:page'
            context['page_pk'] = self.kwargs['pk']
            self.template_name = 'products/products_list.html'
        else:
            context['hot_product'] = get_hot_product()
            context['same_products'] = get_same_products(context['hot_product'])

        context['category'] = category
        context['catalog_menu'] = get_catalog_menu()

        return context


class ProductView(DetailView):
    model = Product
    template_name = 'products/product.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        context['title'] = self.object.name
        context['catalog_menu'] = get_catalog_menu()

        return context


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        # db_profile_by_type(sender, 'UPDATE', connection.queries)

products/templates/products/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' 0 %}"
            {% if request.resolver_match.kwargs.pk == 0 %} class="active"{% endif %}>все
        </a>
    </li>
    {% for link in catalog_menu %}
    <li>
        <a href="{% url 'products:category' link.pk %}"
        {% if request.resolver_match.kwargs.pk|add:'0' == link.pk %} class="active"{% endif %}>
        {{ link.name }}
        </a>
    </li>
    {% endfor %}
</ul>

products/templates/products/includes/inc_pagination.html
{% if paginator.num_pages > 1 %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{% url 'products:page' category.pk|add:'0' page_obj.previous_page_number %}">&larr;</a>
            </li>
        {% endif %}
            <li class="page-item active">
                <span class="page-link">
                страница {{ page_obj.number }} из {{ paginator.num_pages }}
                </span>
            </li>
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'products:page' category.pk|add:'0' page_obj.next_page_number %}">&rarr;</a>
            </li>
        {% endif %}
        </ul>
    </nav>
{% endif %}

products/templates/products/includes/inc_pagination_FBV.html
{% if products.paginator.num_pages > 1 %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if products.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{% url 'products:page' category.pk|add:'0' products.previous_page_number %}">&larr;</a>
            </li>
        {% endif %}
            <li class="page-item active">
                <span class="page-link">
                страница {{ products.number }} из {{ products.paginator.num_pages }}
                </span>
            </li>
        {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'products:page' category.pk|add:'0' products.next_page_number %}">&rarr;</a>
            </li>
        {% endif %}
        </ul>
    </nav>
{% endif %}