adminapp/urls.py
from django.urls import path, re_path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.main, name='main'),

    re_path(r'^users/read/page/(?P<page>[0-9])/$', adminapp.UsersListView.as_view(), name='users_page'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>/', adminapp.UsersUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UsersDeleteView.as_view(), name='user_delete'),

    re_path(r'^categories/read/page/(?P<page>[0-9])/$', adminapp.ProductCategoryListView.as_view(),
            name='categories_page'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/read/category/<int:pk>/', adminapp.ProductListView.as_view(), name='products'),
    re_path(r'^products/read/category/(?P<pk>[0-9])/page/(?P<page>[0-9])/$', adminapp.ProductListView.as_view(), name='products_page'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, contacts, upload_to_base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('upload/', upload_to_base, name='upload'),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

products/urls.py
from django.urls import path
from .views import ProductListView, ProductView

app_name = 'products'

urlpatterns = [
   path('', ProductListView.as_view(), name='index'),
   path('category/<int:pk>/', ProductListView.as_view(), name='category'),
   path('category/<int:pk>/page/<int:page>/', ProductListView.as_view(), name='page'),
   path('product/<int:pk>/', ProductView.as_view(), name='product')
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.models import ShopUser
from products.models import ProductCategory, Product

from authapp.forms import ShopUserEditForm


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

adminapp/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator

from authapp.models import ShopUser
from products.models import ProductCategory, Product

from adminapp.forms import ShopUserAdminEditForm
from adminapp.forms import ProductEditForm, ProductCategoryEditForm


def get_breadcrumb(list_items=(), object={}):
    """
    Create data to render page breadcrumbs
    :param list_items: categories list
    :param object: object with additional data
    :return:
    """
    breadcrumbs = [
        {
            'title': 'главная',
            'link': reverse('admin_staff:main')
        }
    ]

    if not list_items:
        return breadcrumbs

    for module in list_items:
        if module == 'users':
            breadcrumbs.append(
                {
                    'title': 'пользователи',
                    'link': reverse('admin_staff:users')
                }
            )
        elif module == 'products':
            breadcrumbs.append(
                {
                    'title': object.name,
                    'link': reverse('admin_staff:products', args=[object.pk])
                }
            )
        elif module == 'categories':
            breadcrumbs.append(
                {
                    'title': 'категории продуктов',
                    'link': reverse('admin_staff:categories')
                }
            )

    return breadcrumbs


@user_passes_test(lambda u: u.is_superuser)
def main(request):
    title = 'админка'
    context = {
        'title': title
    }
    return render(request, 'adminapp/main.html', context=context)


########################################################################################################################
# -- Users views -------------------------------------------------------------------------------------------------------
########################################################################################################################
class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'objects'
    ordering = ('-is_active', '-is_superuser', '-is_staff', 'username')
    paginate_by = 2

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UsersListView, self).get_context_data(**kwargs)
        context['title'] = 'cписок пользователей'
        context['breadcrumbs'] = get_breadcrumb()
        context['page_url'] = 'adminapp:users_page'
        return context


class UsersCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')
    # fields = '__all__'
    form_class = ShopUserAdminEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UsersCreateView, self).get_context_data(**kwargs)
        context['title'] = 'создание пользователя'
        context['breadcrumbs'] = get_breadcrumb(('users',))
        return context


class UsersUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    form_class = ShopUserAdminEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UsersUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'редактирование'
        context['post_title'] = self.object.username
        context['breadcrumbs'] = get_breadcrumb(('users', ))
        return context

    def get_success_url(self):
        if self.object.pk:
            return reverse('admin_staff:user_update', args=[self.object.pk])
        else:
            return reverse('admin_staff:users')


class UsersDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin_staff:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super(UsersDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'удаление пользователя'
        context['user_title'] = self.object.username
        if self.object.first_name:
            context['user_title'] += ' (' + self.object.first_name
            if self.object.last_name:
                context['user_title'] += ' ' + self.object.last_name
            context['user_title'] += ')'

        context['breadcrumbs'] = get_breadcrumb(('users', ))
        return context


########################################################################################################################
# -- Products Categories views -----------------------------------------------------------------------------------------
########################################################################################################################
class ProductCategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    context_object_name = 'objects'
    ordering = ('-is_active', 'name')
    paginate_by = 2

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryListView, self).get_context_data(**kwargs)
        context['title'] = 'категории товаров'
        context['breadcrumbs'] = get_breadcrumb()
        context['page_url'] = 'adminapp:categories_page'
        return context


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    # fields = '__all__'
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryCreateView, self).get_context_data(**kwargs)
        context['title'] = 'создание категории'
        context['breadcrumbs'] = get_breadcrumb(('categories', ))
        return context


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    # success_url = reverse_lazy('admin_staff:category_update')
    # fields = '__all__'
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'редактирование "' + self.object.name + '"'
        context['breadcrumbs'] = get_breadcrumb(('categories', ))
        return context

    def get_success_url(self):
        if self.object.pk:
            return reverse('admin_staff:category_update', args=[self.object.pk])
        else:
            return reverse('admin_staff:categories')

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']

        if discount:
            self.object.product_set.update(price=F('price') * (1 - discount / 100))

        return super().form_valid(form)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    context_object_name = 'category'
    success_url = reverse_lazy('admin_staff:categories')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.success_url)

########################################################################################################################
# -- Products views ---------------------------------------------------------------------------------------------------
########################################################################################################################
class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    context_object_name = 'objects'
    ordering = ('-is_active', 'name')
    paginate_by = 2

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        query_set = super().get_queryset()
        return query_set.filter(category__pk=self.kwargs['pk'])

    def get_context_data(self, *, object_list=None, **kwargs):

products/views.py
# import json
from django.db import connection
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.views.generic import DetailView, ListView

from .models import ProductCategory, Product


def get_hot_product():
    return Product.objects.filter(is_active=True).order_by('?').first()


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


def get_catalog_menu():
    return ProductCategory.objects.filter(is_active=True)


class ProductListView(ListView):
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'
    ordering = ('price',)
    paginate_by = 3

    def get_queryset(self):
        query_set = super().get_queryset()

        if self.kwargs.get('pk') is None:
            return query_set

        if self.kwargs['pk'] == 0:
            return query_set.filter(is_active=True)
        else:
            return query_set.filter(category__pk=self.kwargs['pk'], is_active=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        category = None
        if self.kwargs.get('pk') is not None:
            category = ProductCategory.objects.filter(pk=self.kwargs['pk']).first()

        if category is None:
            category = ProductCategory(name='все', pk=0)

        context['title'] = 'продукты "'

        if self.kwargs.get('pk') is not None:
            context['title'] = 'продукты "' + category.name + '"'
            context['page_url'] = 'products:page'
            context['page_pk'] = self.kwargs['pk']
            self.template_name = 'products/products_list.html'
        else:
            context['hot_product'] = get_hot_product()
            context['same_products'] = get_same_products(context['hot_product'])

        context['category'] = category
        context['catalog_menu'] = get_catalog_menu()

        return context


class ProductView(DetailView):
    model = Product
    template_name = 'products/product.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        context['title'] = self.object.name
        context['catalog_menu'] = get_catalog_menu()

        return context


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        # db_profile_by_type(sender, 'UPDATE', connection.queries)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
{% load utils %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|capfirst }}
        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/fonts/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/style.css' %}">

    {% block css %}
    {% endblock %}

    <script src="{% static 'adminapp/js/bootstrap.min.js' %}"></script>
    <script src='{% static "adminapp/js/script.js" %}'></script>

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="{{ user.avatar|media_folder_users }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'main' %}" class="nav_logo" target="_blank">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">на сайт</span>
            </a>
            {% include 'adminapp/includes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Выход</span> </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 bg-light">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">{{ title|capfirst }}{% if post_title %} <strong>{{ post_title|capfirst }}</strong>{% endif %}</h1>
            <div class="card mb-4">
                {% if breadcrumbs %}
                    {% include 'adminapp/includes/inc_breadcrumbs.html' %}
                {% endif %}
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
</div>
<!--Container Main end-->
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
        <div class="card-body">
            <div class="table-responsive">
                {% include 'adminapp/includes/inc_pagination.html' %}
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Наименование</th>
                        <th>Товары</th>
                        <th>Редактировать</th>
                        <th>Удалить</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Наименование</th>
                        <th>Товары</th>
                        <th>Редактировать</th>
                        <th>Удалить</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for category in objects %}
                        <tr{% if not category.is_active %} class="deleted-item" {% endif %}>
                            <td>{{ category.name }}</td>
                            <td><a href="{% url 'admin_staff:products' category.pk %}">Товары</a></td>
                            <td class="text-center">
                                <a href="{% url 'admin_staff:category_update' category.pk %}"><i class="fa fa-pencil"></i></a>
                            </td>
                            <td class="text-center">
                                <a class="delete-item-link" href="{% url 'admin_staff:category_delete' pk=category.pk %}">
                                    <i class="fa fa-times-circle"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% include 'adminapp/includes/inc_pagination.html' %}
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'admin_staff:category_create' %}">
                <button class="btn btn-success">Создать категорию</button>
            </a>
        </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
        <div class="card-body">
            <p>Уверены, что хотите удалить категорию <strong>{{ category.name }}?</strong></p>
            <form action="{% url 'admin_staff:category_delete' category.pk %}" method="post">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" value="удалить"> /
                <a class="btn btn-round btn-outline-primary" href="{% url 'admin_staff:categories' %}">Отмена</a>
            </form>
        </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="card-body">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <div class="form-group mt-3">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock %}

adminapp/templates/adminapp/main.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="card-body">
    <p>Главная страница админки</p>
</div>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
        <div class="card-body">
            <p>Уверены, что хотите удалить товар <strong>{{ object.name }}?</strong></p>
            <form action="{% url 'admin_staff:product_delete' object.pk %}" method="post">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" value="удалить"> /
                <a class="btn btn-round btn-outline-primary" href="{% url 'admin_staff:products' object.category.pk %}">Отмена</a>
            </form>
        </div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load utils %}

{% block content %}
            <div class="card-body">
                <div class="table-responsive">
                {% if objects %}
                    {% include 'adminapp/includes/inc_pagination.html' %}
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <th>Просмотр</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <th>Просмотр</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for product in objects %}
                            <tr {% if not product.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td>
                                    {% if product.is_active %}
                                    <a href="{% url 'admin_staff:product_update' pk=product.pk %}">{{ product.name }}</a>
                                    {% else %}{{ product.name }}{% endif %}
                                </td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.price|price_format }} руб.</td>
                                <td class="text-center">
                                    {% if product.is_active %}
                                    <a href="{% url 'admin_staff:product_read' pk=product.pk %}"><i class="fa fa-search"></i></a>
                                    {% else %}&nbsp;{% endif %}
                                </td>
                                <td class="text-center">
                                    {% if product.is_active %}
                                    <a class="delete-item-link" href="{% url 'admin_staff:product_delete' pk=product.pk %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                    {% else %}&nbsp;{% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'adminapp/includes/inc_pagination.html' %}
                {% else %}
                    <p>Список пуст</p>
                {% endif %}
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admin_staff:product_create' category.pk %}">
                    <button class="btn btn-success">Создать товар</button>
                </a>
            </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
            <div class="card-body">
                <p>Уверены, что хотите удалить пользователя <strong>{{ user_title }}?</strong></p>
                <form action="{% url 'admin_staff:user_delete' object.pk %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="удалить"> /
                    <a class="btn btn-round btn-outline-primary" href="{% url 'admin_staff:users' %}">Отмена</a>
                </form>
            </div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
            <div class="card-body">
                <div class="table-responsive">
                    {% include 'adminapp/includes/inc_pagination.html' %}
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in objects %}
                            <tr{% if not user.is_active %} class="deleted-item"{% endif %}>
                                <td><a href="{% url 'admin_staff:user_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>{{ user.last_login }}</td>
                                <td>
                                    <a class="delete-item-link" href="{% url 'admin_staff:user_delete' pk=user.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'adminapp/includes/inc_pagination.html' %}
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
{% endblock %}