authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basket'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.add, name='add'),
    path('remove/<int:pk>/', basketapp.remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, contacts, upload_to_base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('upload/', upload_to_base, name='upload'),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
   path('', ordersapp.OrderList.as_view(), name='orders_list'),
   path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
   path('create/', ordersapp.OrderCreate.as_view(), name='order_create'),
   path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
   path('update/<int:pk>/', ordersapp.OrderUpdate.as_view(), name='order_update'),
   path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
   path('product/<int:pk>/price/', ordersapp.get_product_price),
]

geekshop/views.py
from django.shortcuts import render
from products.models import TestModel
from datetime import datetime

from products.models import Product

from geekshop.utils import get_file_data


def index(request):
    new_products = Product.objects.order_by('?')[2:6]
    content = {
        'title': 'главная',
        'new_products': new_products,
    }
    return render(request, 'index.html', context=content)


def contacts(request):
    content = {
        'title': 'контакты',
    }
    return render(request, 'contacts.html', context=content)


def upload_to_base(request):
    categories = get_file_data('new_product_sections.json')
    for item in categories:
        name = item['name'] + ' (' + str(datetime.now()) + ')'
        category = TestModel(name=name, description=item['description'])
        category.save()

    content = {
        'added': len(categories),
        'total': TestModel.objects.count()
    }
    return render(request, 'upload.html', context=content)

geekshop/templates/includes/menu_inc.html
{% if request.resolver_match.view_name == 'main' %}
<span href="{% url 'main' %}" class="logo"></span>
{% else %}
<a href="{% url 'main' %}" class="logo"></a>
{% endif %}
<ul class="menu">
    {% for item in menu_items %}
    <li><a {% if item.name == request.resolver_match.view_name %}class="active" {% endif %}href="{% url item.name %}">{{ item.title }}</a></li>
    {% endfor %}
    {% if user.is_authenticated %}
       <li>
           <div class="dropdown">
               <a class="nav-link dropdown-toggle" id="navbarDarkDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                   {{ user.first_name|default:'Пользователь' }}
               </a>
               <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <li>
                       <a href="{% url 'auth:edit' %}">профиль</a>
                    </li>
                    <li>
                       <a href="{% url 'ordersapp:orders_list' %}">заказы</a>
                    </li>
                    {% if user.is_superuser %}
                    <li>
                        <a href="{% url 'admin_staff:main' %}" target="_blank" class="admin_link">Админка</a>
                    </li>
                    {% endif %}
               </ul>
           </div>
       </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
          <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
          <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:view' %}" class="basket">
    <span>
        {% if basket and basket.qty != 0 %} {{ basket.qty }} шт.<br> {{ basket.sum }}р.{% endif %}
    </span>
</a>