authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basket'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.add, name='add'),
    path('remove/<int:pk>/', basketapp.remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, contacts, upload_to_base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('upload/', upload_to_base, name='upload'),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

products/urls.py
from django.urls import path
from .views import ProductListView, ProductView

app_name = 'products'

urlpatterns = [
   path('', ProductListView.as_view(), name='index'),
   path('category/<int:pk>/', ProductListView.as_view(), name='category'),
   path('category/<int:pk>/page/<int:page>/', ProductListView.as_view(), name='page'),
   path('product/<int:pk>/', ProductView.as_view(), name='product')
]

products/models.py
from django.db import models

from geekshop import utils


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=True, verbose_name='активность')

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(verbose_name='изображение', upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    is_active = models.BooleanField(default=True, verbose_name='активность')

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @property
    def get_price(self):
        return utils.get_price_format(self.price)


class TestModel(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name

products/views.py
# import json
from django.db import connection
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.views.generic import DetailView, ListView

from .models import ProductCategory, Product


def get_hot_product():
    return Product.objects.filter(is_active=True).order_by('?').first()


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


def get_catalog_menu():
    return ProductCategory.objects.filter(is_active=True)


class ProductListView(ListView):
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'
    ordering = ('price',)
    paginate_by = 3

    def get_queryset(self):
        query_set = super().get_queryset()

        if self.kwargs.get('pk') is None:
            return query_set

        if self.kwargs['pk'] == 0:
            return query_set.filter(is_active=True)
        else:
            return query_set.filter(category__pk=self.kwargs['pk'], is_active=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        category = None
        if self.kwargs.get('pk') is not None:
            category = ProductCategory.objects.filter(pk=self.kwargs['pk']).first()

        if category is None:
            category = ProductCategory(name='все', pk=0)

        context['title'] = 'продукты "'

        if self.kwargs.get('pk') is not None:
            context['title'] = 'продукты "' + category.name + '"'
            context['page_url'] = 'products:page'
            context['page_pk'] = self.kwargs['pk']
            self.template_name = 'products/products_list.html'
        else:
            context['hot_product'] = get_hot_product()
            context['same_products'] = get_same_products(context['hot_product'])

        context['category'] = category
        context['catalog_menu'] = get_catalog_menu()

        return context


class ProductView(DetailView):
    model = Product
    template_name = 'products/product.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        context['title'] = self.object.name
        context['catalog_menu'] = get_catalog_menu()

        return context


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        # db_profile_by_type(sender, 'UPDATE', connection.queries)

products/templates/products/product.html
{% extends 'base.html' %}
{% load static %}
{% load utils %}
{% block morecss %}
<link rel="stylesheet" href="{% static '/products/css/style.css' %}">
{% endblock %}


{% block content %}
		<div class="hero-white">
			<div class="header clearfix">
				{% include 'includes/menu_inc.html' %}
			</div>
		</div>

		<div class="details">
			<div class="links clearfix">
				 {% include 'products/includes/inc_categories_menu.html' %}
				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{{ product.image|media_folder_products }}">
					</div>
					<!-- <div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static '/products/img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static '/products/img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static '/products/img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div> -->
				</div>

				<div class="description">
					<h3 class="big-bold">{{ product.name }}</h3>
					<h3 class="red">{{ product.short_desc }}</h3>
					<p class="price">{{ product.get_price }}<span>руб</span></p>
					<a class="red-button" href="{% url 'basket:add' product.pk %}" title="{{ product.name }}">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{{ product.description }}
					</div>
				</div>
			</div>
		</div>
{% endblock %}

products/templates/products/products.html
{% extends 'base.html' %}
{% load static %}
{% load utils %}
{% block morecss %}
<link rel="stylesheet" href="{% static '/products/css/style.css' %}">
{% endblock %}


{% block content %}
		<div class="hero-white">
			<div class="header clearfix">
				{% include 'includes/menu_inc.html' %}
			</div>
		</div>

		<div class="details">
			<div class="links clearfix">
				 {% include 'products/includes/inc_categories_menu.html' %}
				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{{ hot_product.image|media_folder_products }}">
					</div>
					<!-- <div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static '/products/img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static '/products/img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static '/products/img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div> -->
				</div>

				<div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price">{{ hot_product.get_price }}<span>руб</span></p>
					<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{{ hot_product.description }}
					</div>
				</div>
			</div>
		{% if same_products %}
			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static '/geekshop/img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% for item in same_products %}
					<div class="block">
						<a href="{% url 'products:product' item.pk %}">
							<img src="{{ item.image|media_folder_products }}" alt="{{ item.name }}">
							<div class="text">
								<img src="{% static '/geekshop/img/icon-hover.png' %}" alt="img">
								<h3>{{ item.category.name }}</h3>
								<h4>{{ item.name }}</h4>
								{% if item.description %}
								<p>{{ item.description }}</p>
								{% endif %}
							</div>
						</a>
					</div>
					{% endfor %}
				</div>
			</div>
		{% endif %}
		</div>
{% endblock %}

products/templates/products/products_list.html
{% extends 'base.html' %}
{% load static %}
{% load utils %}
{% block morecss %}
<link rel="stylesheet" href="{% static '/products/css/style.css' %}">
{% endblock %}

{% block content %}
		<div class="hero-white">
			<div class="header clearfix">
				{% include 'includes/menu_inc.html' %}
			</div>
		</div>
        <div class="details">
            <div class="links clearfix">
                {% include 'products/includes/inc_categories_menu.html' %}
            </div>

            <div class="products_list">
                <div class="title clearfix">
                    <h2>Категория: "{{ category.name|title }}"</h2>
                </div>
                <div class="clearfix mb-5"></div>
            {% if products %}
                {% include 'products/includes/inc_pagination.html' %}
                <div class="clearfix mb-5"></div>
                <div class="category-products clearfix">
                    {% for product in products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}" title="{{ product.name }}">
                            <img src="{{ product.image|media_folder_products }}" alt="{{ product.name }}">
							<div class="text">
								<img src="{% static '/geekshop/img/icon-hover.png' %}" alt="{{ product.name }}">
								<h3>{{ product.category.name }}</h3>
								<h4>{{ product.name }}</h4>
								{% if product.description %}
								<p>{{ product.description }}</p>
								{% endif %}
							</div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
                <div class="clearfix mb-5"></div>
                {% include 'products/includes/inc_pagination.html' %}
                <div class="clearfix mb-5"></div>
            {% endif %}
            </div>
        </div>

        <div class="clr"></div>
{% endblock %}